"""empty message

Revision ID: f781813a2af0
Revises: de46ce482915
Create Date: 2023-03-23 23:35:21.282800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f781813a2af0"
down_revision = "de46ce482915"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shows", schema=None) as batch_op:
        batch_op.drop_column("id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shows", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
